### ISSUE TITLE
Convenience Frames: not adapted to URDF

### ISSUE THREAD

**Issue by TanjaSmiley** [bit-bots/bitbots_misc#75]
## Expected behavior

The approach frame should be broadcasted.

## Current behavior

In line 48 and 49 of convenience_frames.cpp a transform to r_toe/ l_toe fails. Therefore the try block fails and the approach frame is not published.

## Steps to Reproduce

1. roslaunch bitbots_body_behavior rviz_behavior_test.launch
2. start rqt tf tree (no approach frame is visible)

## Context (Environment)

- [x] RViz
- [ ] Simulator
- [ ] Robot
- [ ] Local

## Possible Solution

The transform to r_toe and l_toe should be replaced with new transformations to the actual urdf links representing the front of each foot.

**Comment by SammyRamone** [comment]
this is acutally an error of the URDF. l_toe and r_toe should be present and are missing because they were forgot in the onshape model. I can fix this quickly
