### ISSUE TITLE
create complete behavior test in webots

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_misc#80]
The current `simulation.launch` file should be adapted to a) use webots and b) work properly.
- [x] fix launch files
- [x] make simulation work
- [x] make motion work
- [x] make vision work

**Comment by SammyRamone** [comment]
most of the webots work is done in https://github.com/bit-bots/wolfgang_robot/pull/47#issuecomment-730473093

**Comment by SammyRamone** [comment]
rest of the work is done in https://github.com/bit-bots/bitbots_motion/pull/180 https://github.com/bit-bots/bitbots_misc/pull/84 https://github.com/bit-bots/wolfgang_robot/pull/57
it is now possible to start the complete software stack in the simulator. Vision needs to be fixed for simulation. @jaagut @Flova @johagge maybe you can have a look at it

**Comment by timonegk** [comment]
The current config file for the vision should be updated to webots.

**Comment by jaagut** [comment]
@timonegk this is already done.

**Comment by SammyRamone** [comment]
@timonegk is there anything left todo for this issue? otherwise we could close it I think

**Comment by timonegk** [comment]
Localization is still missing

**Comment by jgueldenstein** [comment]
@Flova  what is the status on this?

**Comment by Flova** [comment]
I am currently working on the localization
