### ISSUE TITLE
namespace option such that multiple robots can be launched in simulation

### ISSUE THREAD

**Issue by jgueldenstein** [bit-bots/bitbots_misc#89]

**Comment by jgueldenstein** [comment]
* [ ] wolfgang_robot  https://github.com/bit-bots/wolfgang_robot/pull/71
* [ ] bitbots_world_model l
* [ ] bitbots_vision l
* [ ] particle_filter j
* [ ] bitbots_navigation l
* [ ] center_of_mass j
* [ ] udp_bridge l
* [ ] parallel_parameter_search j
* [ ] bitbots_motion j
* [ ] bitbots_misc l
* [ ] bitbots_behavior l
* [ ] bitbots_lowlevel j
* [ ] humanoid_league_misc j
* [ ] humanoid_league_visualization l
* [ ] bitbots_meta j
* [ ] human_pose_estimation_openvino j
* [ ] humanoid_base_footprint j
* [ ] dynamixel-workbench j
* [ ] bitbots_msgs l
* [ ] bitbots_tools l
* [ ] humanoid_league_msgs l
* [ ] rl-baselines3-zoo j
* [ ] dwa_local_planner j
* [ ] dynamixel_workbench_ros_control j

**Comment by SammyRamone** [comment]
I think we can close this. The parallel parameter search works with the PR https://github.com/bit-bots/wolfgang_robot/pull/120
We do not need to care about the lowlevel for now and it has its own issue open.
